### PR TITLE
laravel 5.5 + newssending refactoring

### PR DESCRIPTION
**Pull request by TimFoerster**
Hey,

I refactored the sending feature again (cause of a bug). I moved the sending away from saving the model. It has a own method now and its called over a button. So hopefully no more unwanted sending newsletters. `send` attribute was removed.

This version requires Laravel 5.5 / php7.

### CODE REVIEW

**Comment by TimFoerster** [comment]
Hey, any updates to this pr?

**Comment by gergo85** [comment]
Sorry for delay, but I have a lot of work. I tested the your PR:

I send a newsletter, but I didn't get it. The mail status is pending. I was waiting for 10-15 minutes.

Furthermore when I wanted to send a test mail, I got the following error:

"Call to undefined method October\Rain\Flash\FlashBag::failed()" on line 221 of /vendor/laravel/framework/src/illuminate/Support/Facedes/Facade.php

I use October 426 and PHP 7.0.24.

**Comment by gergo85** [comment]
@TimFoerster I fixed the FlashBag issue, but the sending mail feature still doesn't work. Please test it!

**Comment by gergo85** [comment]
I fixed the mail sending. Tomorrow I will update the plugin.

**Comment by TimFoerster** [comment]
I'm sorry. My PHP-developer laptop is not starting anymore :/ Don't know if I changed some more.

**Comment by TimFoerster** [comment]
but thanks for your work!

**Comment by TimFoerster** [comment]
Do you got the same problem, that `mail` aka php mail configuration is not working anymore in +420?

**Comment by TimFoerster** [comment]
https://github.com/octobercms/october/issues/3256

**Comment by TimFoerster** [comment]
btw the newsletter look can be changed with this update. Waiting for https://github.com/octobercms/october/pull/3192 to be pulled. Gives you the possibility to disable email branding for the newsletter email layout.

**Pull request merged**
